### ISSUE TITLE
Test keys show as valid ones? 

### ISSUE THREAD

**Issue by vitorpamplona** [obrassard/shc-extractor#20]
Hi all, 

I realized you accept/verify any signed SHC on the interface, even those we create for demos and other non-production environments. Those should not be a "Trusted Party" or a valid certificate in the real world. 

Do you have any plan to add and maintain a Trust Registry with only the keys that have been verified to issue Proof of Vaccinations that effectively happened? 

You can use ours to start if you wish: https://github.com/Path-Check/trust-registry 

We use it on our app and it's working great to filter production keys for all the trash that is out there. 

Happy to help in any way I can. 

Best,

**Comment by obrassard** [comment]
Hello @vitorpamplona, thanks for the idea! This behavior is more or less intended. Indeed, the purpose of this project is at first to allow people to understand how smart health cards work and to help them discover what personal information is contained in their QR code payload. In this sense, a correctly signed SHC will be marked as valid from the perspective of the SHC protocol. 

Also, in Canada at least, merchants and restaurants are not supposed to use third-party applications to validate customers' QR codes, therefore I don't know how much of a need it is to implement this kind of verification in this project.
