### ISSUE TITLE
'sample.png' is detected as null, please convert to image/png

### ISSUE THREAD

**Issue by dcisw** [obrassard/shc-extractor#23]
Hi, I'm getting this error when I run node shc.js 'sample.png', where sample.png is the QR Code sample included with the package.  I tried using another qr code png but still get the same error.  I'm new so I'm sure it's user error but I'd appreciate anyone's input/help.

Thanks!

**Comment by dcisw** [comment]
Ah, I needed to use quotes not apostrophes around the png file name.  Not sure if the usage instructions should be updated on the main code page.

**Comment by obrassard** [comment]
@dcisw What is your operating system ?

**Comment by dcisw** [comment]
> @dcisw What is your operating system ?

Windows 10 Home

**Comment by obrassard** [comment]
It is not impossible that Windows require double quotes for arguments in the CMD, on Unix (Mac / Linux) the simple quotes work 😄

**Comment by dcisw** [comment]
Clearly, Windows is the inferior operating system.  LOL.

Is there a script that goes the other way?  json to qr?

**Comment by obrassard** [comment]
> Is there a script that goes the other way? json to qr?

No, the purpose of this project is SHC decoding. Generating custom QR codes from a custom JSON file won't work since the signature of the custom QR code won't be accepted by official validation apps.

**Comment by TRM13** [comment]
@dcisw If you want to generate then give a look at the walkthrough
https://github.com/dvci/health-cards-walkthrough
In Jupyter Lab format so you can execute directly or copy the code parts to a script.

**Comment by obrassard** [comment]
@dcisw You can learn more about generating custom codes here : https://github.com/obrassard/shc-extractor/discussions/26
